/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardLayoutRouteRouteImport } from './routes/(dashboard)/_layout/route'
import { Route as dashboardLayoutIndexRouteImport } from './routes/(dashboard)/_layout/index'
import { Route as dashboardLayoutDepartmentsRouteImport } from './routes/(dashboard)/_layout/departments'

const dashboardLayoutRouteRoute = dashboardLayoutRouteRouteImport.update({
  id: '/(dashboard)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutIndexRoute = dashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardLayoutRouteRoute,
} as any)
const dashboardLayoutDepartmentsRoute =
  dashboardLayoutDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/departments': typeof dashboardLayoutDepartmentsRoute
  '/': typeof dashboardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/departments': typeof dashboardLayoutDepartmentsRoute
  '/': typeof dashboardLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/_layout': typeof dashboardLayoutRouteRouteWithChildren
  '/(dashboard)/_layout/departments': typeof dashboardLayoutDepartmentsRoute
  '/(dashboard)/_layout/': typeof dashboardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/departments' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/departments' | '/'
  id:
    | '__root__'
    | '/(dashboard)/_layout'
    | '/(dashboard)/_layout/departments'
    | '/(dashboard)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardLayoutRouteRoute: typeof dashboardLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/_layout': {
      id: '/(dashboard)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout/': {
      id: '/(dashboard)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardLayoutIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/departments': {
      id: '/(dashboard)/_layout/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof dashboardLayoutDepartmentsRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
  }
}

interface dashboardLayoutRouteRouteChildren {
  dashboardLayoutDepartmentsRoute: typeof dashboardLayoutDepartmentsRoute
  dashboardLayoutIndexRoute: typeof dashboardLayoutIndexRoute
}

const dashboardLayoutRouteRouteChildren: dashboardLayoutRouteRouteChildren = {
  dashboardLayoutDepartmentsRoute: dashboardLayoutDepartmentsRoute,
  dashboardLayoutIndexRoute: dashboardLayoutIndexRoute,
}

const dashboardLayoutRouteRouteWithChildren =
  dashboardLayoutRouteRoute._addFileChildren(dashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  dashboardLayoutRouteRoute: dashboardLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
