/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardLayoutRouteRouteImport } from './routes/(dashboard)/_layout/route'
import { Route as dashboardLayoutIndexRouteImport } from './routes/(dashboard)/_layout/index'
import { Route as dashboardLayoutDepartmentsIndexRouteImport } from './routes/(dashboard)/_layout/departments/index'
import { Route as dashboardLayoutDepartmentsCreateRouteImport } from './routes/(dashboard)/_layout/departments/create'

const dashboardLayoutRouteRoute = dashboardLayoutRouteRouteImport.update({
  id: '/(dashboard)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutIndexRoute = dashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardLayoutRouteRoute,
} as any)
const dashboardLayoutDepartmentsIndexRoute =
  dashboardLayoutDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutDepartmentsCreateRoute =
  dashboardLayoutDepartmentsCreateRouteImport.update({
    id: '/departments/create',
    path: '/departments/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardLayoutIndexRoute
  '/departments/create': typeof dashboardLayoutDepartmentsCreateRoute
  '/departments': typeof dashboardLayoutDepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardLayoutIndexRoute
  '/departments/create': typeof dashboardLayoutDepartmentsCreateRoute
  '/departments': typeof dashboardLayoutDepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)/_layout': typeof dashboardLayoutRouteRouteWithChildren
  '/(dashboard)/_layout/': typeof dashboardLayoutIndexRoute
  '/(dashboard)/_layout/departments/create': typeof dashboardLayoutDepartmentsCreateRoute
  '/(dashboard)/_layout/departments/': typeof dashboardLayoutDepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/departments/create' | '/departments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/departments/create' | '/departments'
  id:
    | '__root__'
    | '/(dashboard)/_layout'
    | '/(dashboard)/_layout/'
    | '/(dashboard)/_layout/departments/create'
    | '/(dashboard)/_layout/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardLayoutRouteRoute: typeof dashboardLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/_layout': {
      id: '/(dashboard)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout/': {
      id: '/(dashboard)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardLayoutIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/departments/': {
      id: '/(dashboard)/_layout/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof dashboardLayoutDepartmentsIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/departments/create': {
      id: '/(dashboard)/_layout/departments/create'
      path: '/departments/create'
      fullPath: '/departments/create'
      preLoaderRoute: typeof dashboardLayoutDepartmentsCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
  }
}

interface dashboardLayoutRouteRouteChildren {
  dashboardLayoutIndexRoute: typeof dashboardLayoutIndexRoute
  dashboardLayoutDepartmentsCreateRoute: typeof dashboardLayoutDepartmentsCreateRoute
  dashboardLayoutDepartmentsIndexRoute: typeof dashboardLayoutDepartmentsIndexRoute
}

const dashboardLayoutRouteRouteChildren: dashboardLayoutRouteRouteChildren = {
  dashboardLayoutIndexRoute: dashboardLayoutIndexRoute,
  dashboardLayoutDepartmentsCreateRoute: dashboardLayoutDepartmentsCreateRoute,
  dashboardLayoutDepartmentsIndexRoute: dashboardLayoutDepartmentsIndexRoute,
}

const dashboardLayoutRouteRouteWithChildren =
  dashboardLayoutRouteRoute._addFileChildren(dashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  dashboardLayoutRouteRoute: dashboardLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
