/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as dashboardLayoutRouteRouteImport } from './routes/(dashboard)/_layout/route'
import { Route as dashboardLayoutIndexRouteImport } from './routes/(dashboard)/_layout/index'
import { Route as dashboardLayoutVendorsIndexRouteImport } from './routes/(dashboard)/_layout/vendors/index'
import { Route as dashboardLayoutInvoicesIndexRouteImport } from './routes/(dashboard)/_layout/invoices/index'
import { Route as dashboardLayoutEmployeesIndexRouteImport } from './routes/(dashboard)/_layout/employees/index'
import { Route as dashboardLayoutDepartmentsIndexRouteImport } from './routes/(dashboard)/_layout/departments/index'
import { Route as dashboardLayoutCostHeadsIndexRouteImport } from './routes/(dashboard)/_layout/cost-heads/index'
import { Route as dashboardLayoutCompaniesIndexRouteImport } from './routes/(dashboard)/_layout/companies/index'
import { Route as dashboardLayoutVendorsCreateRouteImport } from './routes/(dashboard)/_layout/vendors/create'
import { Route as dashboardLayoutInvoicesCreateRouteImport } from './routes/(dashboard)/_layout/invoices/create'
import { Route as dashboardLayoutEmployeesCreateRouteImport } from './routes/(dashboard)/_layout/employees/create'
import { Route as dashboardLayoutDepartmentsCreateRouteImport } from './routes/(dashboard)/_layout/departments/create'
import { Route as dashboardLayoutCostHeadsCreateRouteImport } from './routes/(dashboard)/_layout/cost-heads/create'
import { Route as dashboardLayoutCompaniesCreateRouteImport } from './routes/(dashboard)/_layout/companies/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutRouteRoute = dashboardLayoutRouteRouteImport.update({
  id: '/(dashboard)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutIndexRoute = dashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardLayoutRouteRoute,
} as any)
const dashboardLayoutVendorsIndexRoute =
  dashboardLayoutVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutInvoicesIndexRoute =
  dashboardLayoutInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutEmployeesIndexRoute =
  dashboardLayoutEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutDepartmentsIndexRoute =
  dashboardLayoutDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutCostHeadsIndexRoute =
  dashboardLayoutCostHeadsIndexRouteImport.update({
    id: '/cost-heads/',
    path: '/cost-heads/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutCompaniesIndexRoute =
  dashboardLayoutCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutVendorsCreateRoute =
  dashboardLayoutVendorsCreateRouteImport.update({
    id: '/vendors/create',
    path: '/vendors/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutInvoicesCreateRoute =
  dashboardLayoutInvoicesCreateRouteImport.update({
    id: '/invoices/create',
    path: '/invoices/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutEmployeesCreateRoute =
  dashboardLayoutEmployeesCreateRouteImport.update({
    id: '/employees/create',
    path: '/employees/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutDepartmentsCreateRoute =
  dashboardLayoutDepartmentsCreateRouteImport.update({
    id: '/departments/create',
    path: '/departments/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutCostHeadsCreateRoute =
  dashboardLayoutCostHeadsCreateRouteImport.update({
    id: '/cost-heads/create',
    path: '/cost-heads/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)
const dashboardLayoutCompaniesCreateRoute =
  dashboardLayoutCompaniesCreateRouteImport.update({
    id: '/companies/create',
    path: '/companies/create',
    getParentRoute: () => dashboardLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof dashboardLayoutIndexRoute
  '/companies/create': typeof dashboardLayoutCompaniesCreateRoute
  '/cost-heads/create': typeof dashboardLayoutCostHeadsCreateRoute
  '/departments/create': typeof dashboardLayoutDepartmentsCreateRoute
  '/employees/create': typeof dashboardLayoutEmployeesCreateRoute
  '/invoices/create': typeof dashboardLayoutInvoicesCreateRoute
  '/vendors/create': typeof dashboardLayoutVendorsCreateRoute
  '/companies': typeof dashboardLayoutCompaniesIndexRoute
  '/cost-heads': typeof dashboardLayoutCostHeadsIndexRoute
  '/departments': typeof dashboardLayoutDepartmentsIndexRoute
  '/employees': typeof dashboardLayoutEmployeesIndexRoute
  '/invoices': typeof dashboardLayoutInvoicesIndexRoute
  '/vendors': typeof dashboardLayoutVendorsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof dashboardLayoutIndexRoute
  '/companies/create': typeof dashboardLayoutCompaniesCreateRoute
  '/cost-heads/create': typeof dashboardLayoutCostHeadsCreateRoute
  '/departments/create': typeof dashboardLayoutDepartmentsCreateRoute
  '/employees/create': typeof dashboardLayoutEmployeesCreateRoute
  '/invoices/create': typeof dashboardLayoutInvoicesCreateRoute
  '/vendors/create': typeof dashboardLayoutVendorsCreateRoute
  '/companies': typeof dashboardLayoutCompaniesIndexRoute
  '/cost-heads': typeof dashboardLayoutCostHeadsIndexRoute
  '/departments': typeof dashboardLayoutDepartmentsIndexRoute
  '/employees': typeof dashboardLayoutEmployeesIndexRoute
  '/invoices': typeof dashboardLayoutInvoicesIndexRoute
  '/vendors': typeof dashboardLayoutVendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(dashboard)/_layout': typeof dashboardLayoutRouteRouteWithChildren
  '/(dashboard)/_layout/': typeof dashboardLayoutIndexRoute
  '/(dashboard)/_layout/companies/create': typeof dashboardLayoutCompaniesCreateRoute
  '/(dashboard)/_layout/cost-heads/create': typeof dashboardLayoutCostHeadsCreateRoute
  '/(dashboard)/_layout/departments/create': typeof dashboardLayoutDepartmentsCreateRoute
  '/(dashboard)/_layout/employees/create': typeof dashboardLayoutEmployeesCreateRoute
  '/(dashboard)/_layout/invoices/create': typeof dashboardLayoutInvoicesCreateRoute
  '/(dashboard)/_layout/vendors/create': typeof dashboardLayoutVendorsCreateRoute
  '/(dashboard)/_layout/companies/': typeof dashboardLayoutCompaniesIndexRoute
  '/(dashboard)/_layout/cost-heads/': typeof dashboardLayoutCostHeadsIndexRoute
  '/(dashboard)/_layout/departments/': typeof dashboardLayoutDepartmentsIndexRoute
  '/(dashboard)/_layout/employees/': typeof dashboardLayoutEmployeesIndexRoute
  '/(dashboard)/_layout/invoices/': typeof dashboardLayoutInvoicesIndexRoute
  '/(dashboard)/_layout/vendors/': typeof dashboardLayoutVendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/companies/create'
    | '/cost-heads/create'
    | '/departments/create'
    | '/employees/create'
    | '/invoices/create'
    | '/vendors/create'
    | '/companies'
    | '/cost-heads'
    | '/departments'
    | '/employees'
    | '/invoices'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/companies/create'
    | '/cost-heads/create'
    | '/departments/create'
    | '/employees/create'
    | '/invoices/create'
    | '/vendors/create'
    | '/companies'
    | '/cost-heads'
    | '/departments'
    | '/employees'
    | '/invoices'
    | '/vendors'
  id:
    | '__root__'
    | '/login'
    | '/(dashboard)/_layout'
    | '/(dashboard)/_layout/'
    | '/(dashboard)/_layout/companies/create'
    | '/(dashboard)/_layout/cost-heads/create'
    | '/(dashboard)/_layout/departments/create'
    | '/(dashboard)/_layout/employees/create'
    | '/(dashboard)/_layout/invoices/create'
    | '/(dashboard)/_layout/vendors/create'
    | '/(dashboard)/_layout/companies/'
    | '/(dashboard)/_layout/cost-heads/'
    | '/(dashboard)/_layout/departments/'
    | '/(dashboard)/_layout/employees/'
    | '/(dashboard)/_layout/invoices/'
    | '/(dashboard)/_layout/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  dashboardLayoutRouteRoute: typeof dashboardLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout': {
      id: '/(dashboard)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout/': {
      id: '/(dashboard)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardLayoutIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/vendors/': {
      id: '/(dashboard)/_layout/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof dashboardLayoutVendorsIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/invoices/': {
      id: '/(dashboard)/_layout/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof dashboardLayoutInvoicesIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/employees/': {
      id: '/(dashboard)/_layout/employees/'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof dashboardLayoutEmployeesIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/departments/': {
      id: '/(dashboard)/_layout/departments/'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof dashboardLayoutDepartmentsIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/cost-heads/': {
      id: '/(dashboard)/_layout/cost-heads/'
      path: '/cost-heads'
      fullPath: '/cost-heads'
      preLoaderRoute: typeof dashboardLayoutCostHeadsIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/companies/': {
      id: '/(dashboard)/_layout/companies/'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof dashboardLayoutCompaniesIndexRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/vendors/create': {
      id: '/(dashboard)/_layout/vendors/create'
      path: '/vendors/create'
      fullPath: '/vendors/create'
      preLoaderRoute: typeof dashboardLayoutVendorsCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/invoices/create': {
      id: '/(dashboard)/_layout/invoices/create'
      path: '/invoices/create'
      fullPath: '/invoices/create'
      preLoaderRoute: typeof dashboardLayoutInvoicesCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/employees/create': {
      id: '/(dashboard)/_layout/employees/create'
      path: '/employees/create'
      fullPath: '/employees/create'
      preLoaderRoute: typeof dashboardLayoutEmployeesCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/departments/create': {
      id: '/(dashboard)/_layout/departments/create'
      path: '/departments/create'
      fullPath: '/departments/create'
      preLoaderRoute: typeof dashboardLayoutDepartmentsCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/cost-heads/create': {
      id: '/(dashboard)/_layout/cost-heads/create'
      path: '/cost-heads/create'
      fullPath: '/cost-heads/create'
      preLoaderRoute: typeof dashboardLayoutCostHeadsCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
    '/(dashboard)/_layout/companies/create': {
      id: '/(dashboard)/_layout/companies/create'
      path: '/companies/create'
      fullPath: '/companies/create'
      preLoaderRoute: typeof dashboardLayoutCompaniesCreateRouteImport
      parentRoute: typeof dashboardLayoutRouteRoute
    }
  }
}

interface dashboardLayoutRouteRouteChildren {
  dashboardLayoutIndexRoute: typeof dashboardLayoutIndexRoute
  dashboardLayoutCompaniesCreateRoute: typeof dashboardLayoutCompaniesCreateRoute
  dashboardLayoutCostHeadsCreateRoute: typeof dashboardLayoutCostHeadsCreateRoute
  dashboardLayoutDepartmentsCreateRoute: typeof dashboardLayoutDepartmentsCreateRoute
  dashboardLayoutEmployeesCreateRoute: typeof dashboardLayoutEmployeesCreateRoute
  dashboardLayoutInvoicesCreateRoute: typeof dashboardLayoutInvoicesCreateRoute
  dashboardLayoutVendorsCreateRoute: typeof dashboardLayoutVendorsCreateRoute
  dashboardLayoutCompaniesIndexRoute: typeof dashboardLayoutCompaniesIndexRoute
  dashboardLayoutCostHeadsIndexRoute: typeof dashboardLayoutCostHeadsIndexRoute
  dashboardLayoutDepartmentsIndexRoute: typeof dashboardLayoutDepartmentsIndexRoute
  dashboardLayoutEmployeesIndexRoute: typeof dashboardLayoutEmployeesIndexRoute
  dashboardLayoutInvoicesIndexRoute: typeof dashboardLayoutInvoicesIndexRoute
  dashboardLayoutVendorsIndexRoute: typeof dashboardLayoutVendorsIndexRoute
}

const dashboardLayoutRouteRouteChildren: dashboardLayoutRouteRouteChildren = {
  dashboardLayoutIndexRoute: dashboardLayoutIndexRoute,
  dashboardLayoutCompaniesCreateRoute: dashboardLayoutCompaniesCreateRoute,
  dashboardLayoutCostHeadsCreateRoute: dashboardLayoutCostHeadsCreateRoute,
  dashboardLayoutDepartmentsCreateRoute: dashboardLayoutDepartmentsCreateRoute,
  dashboardLayoutEmployeesCreateRoute: dashboardLayoutEmployeesCreateRoute,
  dashboardLayoutInvoicesCreateRoute: dashboardLayoutInvoicesCreateRoute,
  dashboardLayoutVendorsCreateRoute: dashboardLayoutVendorsCreateRoute,
  dashboardLayoutCompaniesIndexRoute: dashboardLayoutCompaniesIndexRoute,
  dashboardLayoutCostHeadsIndexRoute: dashboardLayoutCostHeadsIndexRoute,
  dashboardLayoutDepartmentsIndexRoute: dashboardLayoutDepartmentsIndexRoute,
  dashboardLayoutEmployeesIndexRoute: dashboardLayoutEmployeesIndexRoute,
  dashboardLayoutInvoicesIndexRoute: dashboardLayoutInvoicesIndexRoute,
  dashboardLayoutVendorsIndexRoute: dashboardLayoutVendorsIndexRoute,
}

const dashboardLayoutRouteRouteWithChildren =
  dashboardLayoutRouteRoute._addFileChildren(dashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  dashboardLayoutRouteRoute: dashboardLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
